#!/usr/bin/env bash

hc () {
    herbstclient "$@"
}

hc emit_hook reload

config_dir=$(dirname "$0")
$config_dir/keybindings
$config_dir/theme

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# initialize miscellaneous desktop stuff
feh --no-fehbg --bg-scale ~/.config/wallpaper*

# eww daemon
# eww open workspaces

if pgrep dunst; then pkill dunst; fi
dunst

if pgrep picom; then pkill picom; fi
sleep 1
picom --log-file /storage/picom-log.txt --config ~/.config/picom.conf -b

